## Google Data Analytics Project With Python: Bellabeat Case Study

https://medium.com/@mansourianas/google-data-analytics-project-with-python-bellabeat-case-study-fd9ae5d5dd13

1. Daily Activity Data `(dailyActivity_merged.csv)`: This dataset includes information on daily activities such as steps taken, distance traveled, and active minutes.
2. Daily Calories Data `(dailyCalories_merged.csv)`: This dataset contains details about the daily calorie burn of the users.
3. Daily Steps Data `(dailySteps_merged.csv)`: This focuses specifically on the number of steps taken daily by the users.
4. Sleep Day Data `(sleepDay_merged.csv)`: This dataset provides insights into the sleep patterns of the users, like duration of sleep.
5. Weight Log Data `(weightLogInfo_merged.csv)`: This likely includes information on the users' weight changes over time.

In [1]:
import pandas as pd
import numpy as np

In [2]:
daily_activity_data = pd.read_csv("../Data/FitBit-Fitness-Tracker-Data/dailyActivity_merged.csv")
daily_calories_data = pd.read_csv("../Data/FitBit-Fitness-Tracker-Data/dailyCalories_merged.csv")
daily_steps_data = pd.read_csv("../Data/FitBit-Fitness-Tracker-Data/dailySteps_merged.csv")
sleep_day_data = pd.read_csv("../Data/FitBit-Fitness-Tracker-Data/sleepDay_merged.csv")
weight_log_data = pd.read_csv("../Data/FitBit-Fitness-Tracker-Data/weightLogInfo_merged.csv")

In [3]:
missing_values = {
    "daily_activity_data": daily_activity_data.isnull().sum(),
    "daily_calories_data": daily_calories_data.isnull().sum(),
    "daily_steps_data": daily_steps_data.isnull().sum(),
    "sleep_day_data": sleep_day_data.isnull().sum(),
    "weight_log_data": weight_log_data.isnull().sum()
}

missing_values_df = pd.DataFrame(missing_values)
missing_values_df

,daily_activity_data,daily_calories_data,daily_steps_data,sleep_day_data,weight_log_data
ActivityDate,0.0,NaN,NaN,NaN,NaN
ActivityDay,NaN,0.0,0.0,NaN,NaN
BMI,NaN,NaN,NaN,NaN,0.0
Calories,0.0,0.0,NaN,NaN,NaN
Date,NaN,NaN,NaN,NaN,0.0
FairlyActiveMinutes,0.0,NaN,NaN,NaN,NaN
Fat,NaN,NaN,NaN,NaN,65.0
Id,0.0,0.0,0.0,0.0,0.0
IsManualReport,NaN,NaN,NaN,NaN,0.0
LightActiveDistance,0.0,NaN,NaN,NaN,NaN
LightlyActiveMinutes,0.0,NaN,NaN,NaN,NaN
LogId,NaN,NaN,NaN,NaN,0.0
LoggedActivitiesDistance,0.0,NaN,NaN,NaN,NaN
ModeratelyActiveDistance,0.0,NaN,NaN,NaN,NaN
SedentaryActiveDistance,0.0,NaN,NaN,NaN,NaN
SedentaryMinutes,0.0,NaN,NaN,NaN,NaN
SleepDay,NaN,NaN,NaN,0.0,NaN
StepTotal,NaN,NaN,0.0,NaN,NaN
TotalDistance,0.0,NaN,NaN,NaN,NaN
TotalMinutesAsleep,NaN,NaN,NaN,0.0,NaN
TotalSleepRecords,NaN,NaN,NaN,0.0,NaN
TotalSteps,0.0,NaN,NaN,NaN,NaN
TotalTimeInBed,NaN,NaN,NaN,0.0,NaN
TrackerDistance,0.0,NaN,NaN,NaN,NaN
VeryActiveDistance,0.0,NaN,NaN,NaN,NaN
VeryActiveMinutes,0.0,NaN,NaN,NaN,NaN
WeightKg,NaN,NaN,NaN,NaN,0.0
WeightPounds,NaN,NaN,NaN,NaN,0.0

In [4]:
# Checking for duplicate records in each dataset
duplicate_counts = {
    "daily_activity_data": daily_activity_data.duplicated().sum(),
    "daily_calories_data": daily_calories_data.duplicated().sum(),
    "daily_steps_data": daily_steps_data.duplicated().sum(),
    "sleep_day_data": sleep_day_data.duplicated().sum(),
    "weight_log_data": weight_log_data.duplicated().sum()
}

duplicate_counts_df = pd.DataFrame(duplicate_counts, index=["Duplicates"])
duplicate_counts_df

,daily_activity_data,daily_calories_data,daily_steps_data,sleep_day_data,weight_log_data
Duplicates,0,0,0,3,0

In [5]:
sleep_day_data_cleaned = sleep_day_data.drop_duplicates()

In [6]:
# Standardizing the date columns for merging
daily_activity_data['ActivityDate'] = pd.to_datetime(daily_activity_data.loc[:,'ActivityDate'])
daily_calories_data['ActivityDay'] = pd.to_datetime(daily_calories_data.loc[:,'ActivityDay'])
daily_steps_data['ActivityDay'] = pd.to_datetime(daily_steps_data.loc[:,'ActivityDay'])
sleep_day_data_cleaned['SleepDay'] = pd.to_datetime(sleep_day_data_cleaned.loc[:,'SleepDay'])

# Merging the Daily Activity, Daily Calories, and Daily Steps datasets

merged_data = pd.merge(daily_activity_data, daily_calories_data, how='left', left_on=['Id', 'ActivityDate'], right_on=['Id', 'ActivityDay'])
merged_data = pd.merge(merged_data, daily_steps_data, how='left', left_on=['Id', 'ActivityDate'], right_on=['Id', 'ActivityDay'])

# Dropping duplicate columns

merged_data.drop(columns=['ActivityDay_x', 'ActivityDay_y','Calories_y'], inplace=True)
merged_data = merged_data.rename(columns={'Calories_x':'Calories'})

merged_data.head()

C:\Users\SS\AppData\Local\Temp\ipykernel_23236\2956367438.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sleep_day_data_cleaned['SleepDay'] = pd.to_datetime(sleep_day_data_cleaned.loc[:,'SleepDay'])
C:\Users\SS\AppData\Local\Temp\ipykernel_23236\2956367438.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sleep_day_data_cleaned['SleepDay'] = pd.to_datetime(sleep_day_data_cleaned.loc[:,'SleepDay'])

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,StepTotal
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,13162
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,10735
2,1503960366,2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,10460
3,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,9762
4,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,12669

In [7]:
# Merging the Sleep Day Data with the previous merged dataset
final_merged_data = pd.merge(merged_data, sleep_day_data_cleaned, how='left', left_on=['Id', 'ActivityDate'], right_on=['Id', 'SleepDay'])

# Displaying the first few rows of the final merged dataset
final_merged_data.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,StepTotal,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,13162,2016-04-12,1.0,327.0,346.0
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,10735,2016-04-13,2.0,384.0,407.0
2,1503960366,2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,10460,NaT,NaN,NaN,NaN
3,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,9762,2016-04-15,1.0,412.0,442.0
4,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,12669,2016-04-16,2.0,340.0,367.0